<?php

namespace Ormi;

use Exedra\Routing\Call;
use Exedra\Routing\Finding;
use Exedra\Routing\Route;
use Illuminate\Http\Response;
use Ormi\Utilities\Middlewares\IlluminateResponseMiddleware;
use Psr\Http\Message\ServerRequestInterface;

class Context extends Finding
{
    /**
     * @var \Closure|null
     */
    protected $middlewareFactory;

    public function __construct(Route $route, array $parameters = array(), ServerRequestInterface $request = null, \Closure $middlewareFactory = null)
    {
        $this->middlewareFactory = $middlewareFactory;

        parent::__construct($route, $parameters, $request);
    }

    protected function createCallStack(array $middlewares, array $decorators, Call $resolver)
    {
        // covert any response back to laravel request
        $middlewares[] = new Call([new IlluminateResponseMiddleware(), 'handle']);

        return parent::createCallStack($middlewares, $decorators, $resolver); // TODO: Change the autogenerated stub
    }

    protected function createMiddleware($class)
    {
        return call_user_func_array($this->middlewareFactory, [$class]);
    }
}
